blueprint:
  name: "VA - Display alarms "
  author: "Lone baggie"
  homeassistant:
    min_version: 2024.6.0
  description: >
    ### 🕰 Displays current alarms on screen. Needs voice alarms integration. .
  domain: automation 
  input:
    path:
      name: Dashboard display
      description: Enter dashboard to display on device. 
      default: /view-assist/voice-alarms
      selector:
        text:
    voice_command_options:
      name: Alarm Phrases
      icon: mdi:account-voice
      collapsed: false
      description: >
        Custom voice sentences that will trigger the alarms screen.

        <br>

        <details>
          <summary><b>ℹ️ Click to view the Voice Command Syntax Guide</b></summary>
          <br>
          When editing the phrases below, use these rules to tweak your phrases:
          
          * <b>[Square Brackets]</b> = Optional words. Matches with or without them.
            * *Example:* `[what is] the weather` matches both "the weather" and "what is the weather".
            
          * <b>(Pipes | inside | parentheses)</b> = Alternative words (OR). Matches any single phrase.
            * *Example:* `(tell me|give me)` matches "tell me..." or "give me...".
        </details>
      input:
        alarm_sentence:
          name: Alarm Command 
          description: The phrase used to display the alarms.
          default: "show [the] alarms"
          selector:
            text:
              multiple: true

mode: single

trigger:
  - trigger: conversation
    command: !input alarm_sentence

condition: []

action:
  - variables:
      target_satellite_device: '{{ view_assist_entity(trigger.device_id) }}'
      path: !input path
  - action: view_assist.navigate
    data:
      device: '{{target_satellite_device}}'
      path: '{{path}}'

