blueprint:
  name: View Assist Volume Sync
  description: >-
    Syncs the volume of the pysical volume of the device to the media player. If using Music assistant. 
    
  author: Lonebaggie
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  input:
    volume_number:
      name: Volume Number Entity
      description: The hardware volume of device (normally music volume).
      selector:
        entity:
          integration: vaca
          domain: number
          multiple: true
mode: single

# Declare blueprint inputs as Jinja-accessible variables
triggers:
  - trigger: state
    entity_id: !input volume_number



actions:
  - variables:
     volume: "{{trigger.entity_id}}"
     dev_id: "{{ device_id(volume)}}"
     matched_sensor: "{{view_assist_entity(dev_id)}}"
     sat: "{{ state_attr(matched_sensor,'mic_device') }}"
     media: "{{ state_attr(matched_sensor,'musicplayer_device') }}"
  - if:
      - condition: template
        value_template: "{{ is_state(sat, 'idle') }}"
    then:
      - variables:
          wait: 0
    else:
      - variables:
          wait: 4

  - delay:
      seconds: "{{ wait }}"

  - action: media_player.volume_set
    target:
      entity_id: "{{ media }}"
    data:
      volume_level: "{{ (trigger.to_state.state | float(0) / 18) | round(2) }}"