blueprint:
  name: "VA - Turn off screen in low light"
  author: "Lone baggie"
  homeassistant:
    min_version: 2024.6.0
  description: >-
    Turns off the screen in low light levels
  domain: automation
  input:
    light_sensors:
      name: View Assist Light Sensors
      description: Select the illuminance sensors from your View Assist satellite devices.
      selector:
        entity:
          domain: sensor
          device_class: illuminance
          integration: vaca
          multiple: true
    threshold_lux:
      name: Illuminance Threshold (Lux)
      description: Light level threshold for dark vs light state.
      default: 5
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lx
          mode: box

mode: parallel
max: 10

triggers:
  - trigger: illuminance.crossed_threshold
    target:
      entity_id: !input light_sensors
    options:
      threshold:
        type: below
        value:
          active_choice: number
          number: !input threshold_lux
      for:
        hours: 0
        minutes: 0
        seconds: 10
    id: dark
  - trigger: illuminance.crossed_threshold
    target:
      entity_id: !input light_sensors
    options:
      threshold:
        type: above
        value:
          active_choice: number
          number: !input threshold_lux
      for:
        hours: 0
        minutes: 0
        seconds: 10
    id: light


action:
  - variables:
      trigger_id: "{{ trigger.id }}"
      trigger_entity: "{{ trigger.entity_id }}"

      
      # Derived target entity string
      target_entity: >-
        {{ trigger_entity.replace("sensor", "switch").replace("light_level","screen") }}
  - choose:
      - conditions:
          - condition: trigger
            id: 'light'
        sequence: 
          - action: switch.turn_on
            metadata: {}
            target:
              entity_id: '{{target_entity}}'
            data: {}
      - conditions:
          - condition: trigger
            id: 'dark'
        sequence: 
          - action: switch.turn_off
            metadata: {}
            target:
              entity_id: '{{target_entity}}'